### ISSUE TITLE
ImportError: No module named pysteam.steam

### ISSUE THREAD

**Issue by Bleda2** [scottrice/Ice#219]
Hi all,

I've tried setting up Ice several times, read the readme 's  and looked at the FAQ's.
I think I set it up correctly but when i run ice.py I get the following error:
(copied from stderr.log)

Traceback (most recent call last):
  File "C:\emulators\ice 4\src\ice.py", line 7, in <module>
    from ice.runners import command_line_runner
  File "C:\emulators\ice 4\src\ice\runners\command_line_runner.py", line 9, in <module>
    from pysteam.steam import Steam
ImportError: No module named pysteam.steam

Could anyone give me some adivce?
Thank you all in advance.
/Bleda2

(I'm new to both python and Github so i'm sorry if i make some kind of rookie mistake ^_^ )

**Comment by Slip7000** [comment]
Hi all i got an error on my Mac running ICE, please be so kind to assist:

Traceback (most recent call last):
  File "/Users/Slip7000/Emulators/Ice/ice/**main**.py", line 7, in <module>
    from cli import CommandLineRunner
  File "ice/cli/**init**.py", line 2, in <module>
    from runner import CommandLineRunner
  File "ice/cli/runner.py", line 10, in <module>
    from pysteam.steam import get_steam, Steam
ImportError: No module named pysteam.steam

this the error i got ...
