### ISSUE TITLE
Failure on initial run of python src/ice.py

### ISSUE THREAD

**Issue by Isaacroth** [scottrice/Ice#240]
Traceback (most recent call last):
  File "src/ice.py", line 7, in <module>
    from ice.runners import command_line_runner
  File "/Users/**********/Desktop/Ice/src/ice/runners/command_line_runner.py", line 8, in <module>
    from ice_engine import IceEngine
  File "/Users/**********/Desktop/Ice/src/ice/runners/ice_engine.py", line 15, in <module>
    from ice.environment_checker import EnvironmentChecker
  File "/Users/**********/Desktop/Ice/src/ice/environment_checker.py", line 7, in <module>
    import psutil
ImportError: No module named psutil

An error has occurred! A copy of the crash report has been saved to 'error.log'.
If this continues please submit an issue on our Github page (http://github.com/scottrice/Ice)

((((I believe psutil is a 3rd party module.  I claims to support OSX, but all the installer packages are for Windows.  I'm running this install on OSX Mavericks using your Mac instructions))))

**Comment by scottrice** [comment]
(Sorry for the late reply, just saw this)

psutil is indeed a third party module. You will need to install it (and the other dependencies) before Ice will work. The best way to do this is to run `python setup.py install`.

Hope this helps.
