### ISSUE TITLE
Console.txt optional setting "rom directory" not working

### ISSUE THREAD

**Issue by Wolfereign** [scottrice/Ice#241]
so here is the console I'm trying to get to work:

[Playstation Portable]
nickname=psp
emulator=RA_PSP
extensions=zip, iso
roms directory=C:\Emulation\Platforms\PSP\Roms\
prefix=[PSP]
icon=C:\Emulation\Platforms\PSP\Artwork\icon.png
images directory=C:\Emulation\Platforms\PSP\Artwork\SteamGrid\

However when I run ice.exe it doesn't find the roms unless I set the nickname to the rom directory, but then consolegrid doesn't work.  how do I get this to work so I can use a custom rom directory and still use console grid?  Also Images directory, Icon directories, and prefix don't seem to be working either with the setting listed above or with nickname set to rom folder path.

Not sure what the problem is because theres no errors in log.txt with the settings above.

When I set nickname to rom folder path I get this error:
[11/04/14 14:28:07] ---Downloading grid images
[11/04/14 14:28:07] There was a problem with '[Grid Images] Source' in config.txt
[11/04/14 14:28:07] The current value is set to 'consolegrid.com/api/top_picture'
[11/04/14 14:28:07] The source of game images is unavailable.
Traceback (most recent call last):
  File "string", line 45, in module
  File "string", line 38, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.grid_image_manager", line 84, in update_user_images
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.grid_image_manager", line 65, in find_image_for_rom
ConfigError: '[Grid Images] Source || The source of game images is unavailable.'

**Comment by scottrice** [comment]
Sorry for the late reply, just saw this issue.

It looks like you are using the exe of Ice. The `roms directory` setting is only available in the most recent source. I plan to update the exe in the near future (read - next week or so), but to solve your issue now your best bet is to run the source.
