### ISSUE TITLE
AssertionError: Path `%s` does not exist.

### ISSUE THREAD

**Issue by leetpeet** [scottrice/Ice#246]
Running on Linux,  help plz.
Thanks.

error.log
Traceback (most recent call last):
  File "src/ice.py", line 11, in <module>
    runner.run(sys.argv)
  File "/home/kodi/ice/src/ice/runners/command_line_runner.py", line 15, in run
    engine = IceEngine()
  File "/home/kodi/ice/src/ice/runners/ice_engine.py", line 38, in __init__
    ConfigFileBackingStore(emulators_data_path),
  File "/home/kodi/ice/src/ice/configuration.py", line 65, in __init__
    self.emulator_manager.initialize()
  File "/home/kodi/ice/src/ice/persistence/backed_object_manager.py", line 38, in initialize
    self.create(identifier)
  File "/home/kodi/ice/src/ice/persistence/backed_object_manager.py", line 54, in create
    obj = self.new(identifier)
  File "/home/kodi/ice/src/ice/persistence/emulator_manager.py", line 18, in new
    return Emulator(self.backing_store, identifier)
  File "/home/kodi/ice/src/ice/emulator.py", line 35, in __init__
    assert os.path.exists(self.location), "Path `%s` does not exist."
AssertionError: Path `%s` does not exist.

consoles.txt
[Nintendo Entertainment System]
nickname=NES
emulator=retroarch_nes
roms directory=/var/files/Roms/NES

[Super Nintendo]
nickname=SNES
emulator=retroarch_snes
roms directory=/var/files/Roms/SNES

[Playstation 1]
nickname=PS1
emulator=retroarch_ps1
roms directory=/var/files/Roms/PS1

[Sega Genesis]
nickname=Genesis
emulator=retroarch_genesis
rom directory=/var/files/Roms/Genesis

#[Nintendo Gamecube]
#nickname=Gamecube
#emulator=retroarch_gc

#[Playstation 2]
#nickname=PS2
#emulator=retroarch_ps2

[Turbografx-16]
nickname=Turbografx
emulator=retroarch_turbo
rom directory=/var/files/Roms/TurboGrafx-16

emulators.txt

#Retroarch

[retroarch_nes]
location=retroarch
command=%l -f -L /usr/lib/libretro/libretro-nestopia.so %r

[retroarch_snes]
location=retroarch
command=%l -f -L /usr/lib/libretro/libretro-bsnes-balanced.so %r

#[retroarch_psx]
#location=retroarch
#command=%l -f -L /usr/lib/libretro/libretro-nestopia.so %r

[retroarch_genesis]
location=retroarch
command=%l -f -L /usr/lib/libretro/libretro-genplus.so %r

#[retroarch_ScummVM]
#location=retroarch
#command=%l -f -L /usr/lib/libretro/libretro-nestopia.so %r

#[retroarch_GBA]
#location=retroarch
#command=%l -f -L /usr/lib/libretro/libretro-nestopia.so %r

#[retroarch_N64]
#location=retroarch
#command=%l -f -L /usr/lib/libretro/libretro-nestopia.so %r

#Retroarch end

**Comment by scottrice** [comment]
So it looks like this line of code is checking to make sure that an emulator exists at the location you specified. I'm assuming the issue here is that `retroarch` is not a file that exists in the current directory, but it is something that resolves when you use the `$PATH` variable.

So the quick fix for you would be to use `location=/usr/bin/retroarch` (or whatever the absolute path to retroarch actually is). For Ice I need to make it resolve paths using the `$PATH` variable, but before I do I need to make sure Steam would understand it. If it doesn't then I need to output a better error message in this situation.
