### ISSUE TITLE
Unable to run Ice

### ISSUE THREAD

**Issue by puchimatto** [scottrice/Ice#271]
I have downloaded Ice and tried to run it but it gives me this error:

=========================Starting Ice
####################################
An Error has occurred:
invalid literal for int() with base 10: 'anonymous'
####################################
Close the window, or hit enter to exit...

Ive looked for some solution but hasn´t been able to figure it out, I have already tried on two different computers with windows 7 and 8.1, and they both gave me the same error  Am I doing something wrong here? Do I need to install something else before?

Thanks

**Comment by supercore23** [comment]
I'm having the exact same issue. 

Here's the log info:

[03/27/15 21:53:45] Detected Console: Nintendo Gamecube => Dolphin
[03/27/15 21:53:45] Detected Console: Nintendo Wii => Dolphin
[03/27/15 21:53:45] ####################################
[03/27/15 21:53:45] An Error has occurred:
[03/27/15 21:53:45] invalid literal for int() with base 10: 'anonymous'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 24, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.steam_user_manager", line 180, in user_ids_on_this_machine
ValueError: invalid literal for int() with base 10: 'anonymous'
[03/27/15 21:53:45] ####################################

**Comment by scottrice** [comment]
This is due to an `anonymous` folder being left where Steam normally leaves folders named after user ids. The easiest fix for this is to go to `C:\Program Files (x86)\Steam\userdata` and delete the `anonymous` folder. I believe it just contains the settings for the guest account.

This has actually already been fixed in the current source of Ice (which means if you dont want to delete the `anonymous` folder you can always just run that), but the `.exe` file was built before the fix went in so it still has this bug. Since the source already has the fix there is nothing actionable for me to do here code-wise so I am going to close the task.

**Comment by supercore23** [comment]
Thanks Scott! Great work on this project.
