### ISSUE TITLE
invalid literal for int() with base 10: 'anonymous'

### ISSUE THREAD

**Issue by TmB2084** [scottrice/Ice#282]
What's the problem? I don't understand it.
ICE works not longer for me. :(

[05/04/15 20:00:51] =========================Starting Ice
[05/04/15 20:00:51] Detected Emulator: VisualBoyAdvance
[05/04/15 20:00:51] Detected Emulator: Project64
[05/04/15 20:00:51] Detected Emulator: ZSNES
[05/04/15 20:00:51] Emulator '' not found for Nintendo DS. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Playstation 2. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Playstation 1. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Nintendo Entertainment System. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Sega Dreamcast. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Sega Genesis. Ignoring
[05/04/15 20:00:51] Emulator '' not found for Nintendo Gamecube. Ignoring
[05/04/15 20:00:52] Emulator '' not found for Nintendo Wii. Ignoring
[05/04/15 20:00:52] Detected Console: Super Nintendo => ZSNES
[05/04/15 20:00:52] Detected Console: Gameboy Advance => VisualBoyAdvance
[05/04/15 20:00:52] Detected Console: Nintendo 64 => Project64
[05/04/15 20:00:52] Detected Console: Nintendo Gameboy => VisualBoyAdvance
[05/04/15 20:00:52] ####################################
[05/04/15 20:00:52] An Error has occurred:
[05/04/15 20:00:52] invalid literal for int() with base 10: 'anonymous'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 24, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.steam_user_manager", line 180, in user_ids_on_this_machine
ValueError: invalid literal for int() with base 10: 'anonymous'
[05/04/15 20:00:52] ####################################

**Comment by markubiak** [comment]
I am getting this same issue

**Comment by brentax** [comment]
I'm seeing the same as well.

```shell
Traceback (most recent call last):
  File "E:\Brent\Documents\Code\ice\src\ice.py", line 11, in <module>
    runner.run(sys.argv)
  File "E:\Brent\Documents\Code\ice\src\ice\runners\command_line_runner.py", line 27, in run
    emulators_override=options.emulators,
  File "E:\Brent\Documents\Code\ice\src\ice\runners\ice_engine.py", line 50, in __init__
    self.users = self.steam.local_users()
  File "C:\Python27\lib\site-packages\pysteam-0.1.3-py2.7.egg\pysteam\steam.py", line 77, in local_users
    u = user.User(self, int(entry))
ValueError: invalid literal for int() with base 10: 'anonymous'
```

**Comment by DIYglenn** [comment]
I seem to have the same problems. Some details:

- Windows 10 Pro, 64 bit
- Steam installed on D:\Steam
- Rom folder set in config to "D:\Games\ROMs" (folders not existing)

Run Ice from D:\Games\Ice:
```
=========================Starting Ice
Creating ROMs directory at D:\Games\ROMs
####################################
An Error has occurred:
invalid literal for int() with base 10: 'anonymous'
####################################

Close the window, or hit enter to exit...
```
The folders are created. I tried deleting and re-running as administrator, no difference unfortunately, it still stops with the same error after creating the folder. 
The permissions seems to be correct on the folders created. 

Any idea why I can't make it run?

**Comment by esdf** [comment]
same problem as DIYglenn

**Comment by esdf** [comment]
@DIYglenn had the same problem, fixed by going to steam\userdatta dir and deleting "anonymous" folder. basically the program is looking for integer and breaks on string. then what i suggest doing is delete all the folders inside and just log in with the account you want to use ice with. exit, set up your configs, re-run ice and it should work.

**Comment by hearwa** [comment]
Hello, I looked through the source code and found the issue. It's not actually Scott's issue. He uses a module called "pysteam" and the issue happens there. If you have a user called "anonymous" in your steam's userdata folder (C:\Program Files (x86)\Steam\userdata on my machine) this will occur.

The temporary fix is thankfully very easy -- delete the "userdata" folder!
