### ISSUE TITLE
Weird error after adding roms.

### ISSUE THREAD

**Issue by HoodlumDTX** [scottrice/Ice#314]
[11/26/15 21:21:03] =========================Starting Ice
[11/26/15 21:21:03] Detected Emulator: mednafen
[11/26/15 21:21:03] Emulator '' not found for Nintendo DS. Ignoring
[11/26/15 21:21:03] Emulator '' not found for Playstation 2. Ignoring
[11/26/15 21:21:03] Emulator '' not found for Sega Dreamcast. Ignoring
[11/26/15 21:21:03] Emulator '' not found for Nintendo Gamecube. Ignoring
[11/26/15 21:21:03] Emulator '' not found for Nintendo 64. Ignoring
[11/26/15 21:21:03] Emulator '' not found for Nintendo Wii. Ignoring
[11/26/15 21:21:03] Detected Console: Super Nintendo => mednafen
[11/26/15 21:21:03] Detected Console: Playstation 1 => mednafen
[11/26/15 21:21:03] Detected Console: Nintendo Entertainment System => mednafen
[11/26/15 21:21:03] Detected Console: Gameboy Advance => mednafen
[11/26/15 21:21:03] Detected Console: Sega Genesis => mednafen
[11/26/15 21:21:03] Detected Console: Nintendo Gameboy => mednafen
[11/26/15 21:21:04] ---------------Running for user 153692781
[11/26/15 21:21:04] ####################################
[11/26/15 21:21:04] An Error has occurred:
[11/26/15 21:21:04] 'utf8' codec can't decode byte 0xbd in position 6: invalid start byte
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 33, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 91, in sync_roms
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 78, in remove_deleted_roms_from_steam
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom", line 53, in to_shortcut
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom", line 40, in name
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\encodings.utf_8", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xbd in position 6: invalid start byte
[11/26/15 21:21:04] ####################################

I don't know what this means. I did add like 600 roms from various flash drives I had.

**Comment by ProfessorKaos64** [comment]
I get the same error, even with the latest 1.0.0 release.
