### ISSUE TITLE
Error.log

### ISSUE THREAD

**Issue by glitchninja2000** [scottrice/Ice#318]
I keep getting errors, no matter what I do with the settings. I'm running [Python 2.7.11](https://www.python.org/downloads/release/python-2711/) with [El Captain](http://www.apple.com/osx/?cid=wwa-us-kwg-mac) on a [MacBook Air](http://www.apple.com/macbook-air/?afid=p238%7Cs67xqigsC-dc_mtid_1870765e38482_pcrid_91262097487_&cid=aos-us-kwg-mac-slid-).

Traceback (most recent call last):
  File "/Users/NewMactop/Downloads/Ice-master/src/ice.py", line 7, in <module>
    from ice.runners import command_line_runner
  File "/Users/NewMactop/Downloads/Ice-master/src/ice/runners/command_line_runner.py", line 10, in <module>
    from ice_engine import IceEngine
  File "/Users/NewMactop/Downloads/Ice-master/src/ice/runners/ice_engine.py", line 9, in <module>
    from pysteam.steam import Steam
ImportError: No module named pysteam.steam

**Comment by scottrice** [comment]
You need to run `python setup.py install` before you run Ice.

Thanks!
