### ISSUE TITLE
Setting up Ice on Mac?

### ISSUE THREAD

**Issue by snipes040** [scottrice/Ice#333]
Noob here, is there something that I  am missing in terms of setting up Ice on MAC?  Any help would be awesome!

**Comment by scottrice** [comment]
What exactly are you having trouble with? I do all of my development on a Mac, so it should work without much issue.

**Comment by CyricPL** [comment]
Hi Scott - I came across this looking for the same guidance, and I am not sure if this was ever resolved for Snipes040. The issue is that I really don't know how to get Ice working in Mac OS X at all. I see the EXE file in the main download, but should I use a Wine container to run that? Or am I supposed to get the source files that then do stuff with Python and the Terminal - and if that is the case, I literally have no idea what I am doing and there is no tutorial to show me how. I was able to get Ice working on a Bootcamp partition so that I could run ROMs through Steam Link, because the Windows install is easy, but that still makes me reboot my computer just to get at it. I really want to get it working under OS X, and I think a clear step-by-step guide on the main site would be really helpful.

**Comment by Slip7000** [comment]
Hi, I also really like to have a small guide to get myself going on the mac! I am stuck on the pysteam section, installed PIP and Python. A step-by-step guide will be nice.

my error log:

Traceback (most recent call last):
  File "/Users/##USERNAME##/Emulators/Ice/ice/**main**.py", line 7, in <module>
    from cli import CommandLineRunner
  File "ice/cli/**init**.py", line 2, in <module>
    from runner import CommandLineRunner
  File "ice/cli/runner.py", line 10, in <module>
    from pysteam.steam import get_steam, Steam
ImportError: No module named pysteam.steam

Please...
