### ISSUE TITLE
Issues with new backup dir method / dry-run code

### ISSUE THREAD

**Issue by ProfessorKaos64** [scottrice/Ice#348]
```
=========== Starting Ice ===========
=========== User: anonymous ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice/runners/ice_engine.py", line 155, in run
    self.main(dry_run=dry_run)
  File "ice/runners/ice_engine.py", line 132, in main
    self.run_for_user(user_context, dry_run=dry_run)
  File "ice/runners/ice_engine.py", line 147, in run_for_user
    backups.create_backup_of_shortcuts(self.config, user)
  File "ice/backups.py", line 51, in create_backup_of_shortcuts
    backup_dir = backup_directory(config)
  File "ice/backups.py", line 34, in backup_directory
    backup_dir = config.backup_directory()
  File "ice/configuration.py", line 86, in backup_directory
    None
  File "ice/configuration.py", line 48, in _get_directory_from_store
    path = self.config_backing_store.get(identifier, key, default)
  File "ice/persistence/config_file_backing_store.py", line 41, in get
    val = self.configParser.get(ident, key.lower())
  File "/usr/lib/python2.7/ConfigParser.py", line 330, in get
    raise NoSectionError(section)
NoSectionError: No section: 'Storage'

Close the window, or hit enter to exit...
```

The user log path I have set shows the same bug report. 

Packaging files:  
https://github.com/ProfessorKaos64/SteamOS-Tools-Packaging/tree/brewmaster/ice

**Comment by ProfessorKaos64** [comment]
Thank you Scott. I'll test this commit later today.
