### ISSUE TITLE
new executable problem 

### ISSUE THREAD

**Issue by lufykun** [scottrice/Ice#358]
hi scott 

thank you  for new app, best wish for this year.

i try to launch  the new app 

 my error log 
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\command_line_runner.py", line 12, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\ice_engine.py", line 14, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\backups.py", line 10, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\logs.py", line 66, in <module>
  File "ice\logs.py", line 53, in create_logger
  File "logging\handlers.py", line 117, in __init__
  File "logging\handlers.py", line 64, in __init__
  File "logging\__init__.py", line 903, in __init__
  File "logging\__init__.py", line 926, in _open
IOError: [Errno 2] No such file or directory: u'C:\\Users\\steambox\\AppData\\Local\\Scott Rice\\Ice\\ice.log'

need install python 2.7 ?

**Comment by scottrice** [comment]
Nope you shouldn't need to install Python, you've found a legit bug. Since the logger is created at import time the log directory might not exist. I'll release a new version soon.

In the meantime you can fix the error by making the directory "C:\Users\steambox\AppData\Local\Scott Rice\Ice"

**Comment by lufykun** [comment]
i'm happy to help you  
 thank a lot for your work

**Comment by RobLoach** [comment]
> In the meantime you can fix the error by making the directory

Yup, that did it.
```
mkdir -p ~/.config/ice
```

Do you have an idea of how to fix this? Was thinking perhaps checking the config directory existence in `create_logger()` of `logs.py`.

**Comment by scottrice** [comment]
@RobLoach Yup, thats exactly what I was thinking.

Fix incoming.
