### ISSUE TITLE
Constantly getting this error log

### ISSUE THREAD

**Issue by Arcanous98** [scottrice/Ice#363]
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\command_line_runner.py", line 12, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\ice_engine.py", line 14, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\backups.py", line 10, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\logs.py", line 66, in <module>
  File "ice\logs.py", line 53, in create_logger
  File "logging\handlers.py", line 117, in __init__
  File "logging\handlers.py", line 64, in __init__
  File "logging\__init__.py", line 903, in __init__
  File "logging\__init__.py", line 926, in _open
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Usuario\\AppData\\Local\\Scott Rice\\Ice\\ice.log'

I don't even know why does it ask that directory, as i've double checked to replace all the config file directories with my own. Any help?

**Comment by LonelyTVy** [comment]
Scott has commited a fix to this to the source code, however it appears to not have made it to the release that's for download. 

But there is a fix, navigate to your C:\Users\<user name>\AppData\Local and create a folder called "Scott Rice" then inside of that create another directory and name it "Ice". That will fix it.

**Comment by Arcanous98** [comment]
Works fine. Thanks
