### ISSUE TITLE
[Errno 2]

### ISSUE THREAD

**Issue by mlreinke** [scottrice/Ice#375]
After detecting the emulator and list of ROMS it fails as below.  In my userdata directory there is 0 and two other numbers.  0 doesn't have a config directory and the other two have \config but no shortcuts.vdf.  If I create the \config directory then it runs through just fine.  

[03/27/16 09:03:07] ####################################
[03/27/16 09:03:07] An Error has occurred:
[03/27/16 09:03:07] [Errno 2] No such file or directory: u'c:/program files (x86)/steam\\userdata\\0\\config\\shortcuts.vdf'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 35, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.steam_shortcut_manager", line 202, in save
IOError: [Errno 2] No such file or directory: u'c:/program files (x86)/steam\\userdata\\0\\config\\shortcuts.vdf'
[03/27/16 09:03:07] ####################################

**Comment by Anthony817** [comment]
Same here!

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\command_line_runner.py", line 12, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\ice_engine.py", line 14, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\backups.py", line 10, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\logs.py", line 66, in <module>
  File "ice\logs.py", line 53, in create_logger
  File "logging\handlers.py", line 117, in **init**
  File "logging\handlers.py", line 64, in **init**
  File "logging__init__.py", line 903, in **init**
  File "logging__init__.py", line 926, in _open
IOError: [Errno 2] No such file or directory: u'C:\Users\antdo\AppData\Local\Scott Rice\Ice\ice.log'
