### ISSUE TITLE
ROMs directory constantly giving me errors.

### ISSUE THREAD

**Issue by spiral6** [scottrice/Ice#379]
I'm not sure what's going on, but setting the ROM directory for each individual emulator doesn't work. Neither does setting the global ROMs directory to a folder and restoring the consoles.txt back to default. 

[04/10/16 11:46:08] ####################################
[04/10/16 11:47:04] =========================Starting Ice
[04/10/16 11:47:04] ####################################
[04/10/16 11:47:04] An Error has occurred:
[04/10/16 11:47:04] 'roms directory'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 20, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.filesystem_helper", line 64, in roms_directory
KeyError: 'roms directory'
[04/10/16 11:47:04] ####################################

**Comment by spiral6** [comment]
Never mind, trying a different config file worked. Closing.
