### ISSUE TITLE
Regarding Issue #257 / #292 regarding new build.

### ISSUE THREAD

**Issue by imkrut** [scottrice/Ice#386]
Can't make the version linked (https://github.com/scottrice/Ice/releases/download/1.0.0/Ice.zip) work.

Is Python required for it to run? I also tried the version on http://scottrice.github.io/Ice/ to see if it was updated, but it doesn't seem to be the case.

This is the error log:

> Traceback (most recent call last):
>   File "<string>", line 7, in <module>
>   File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>   File "ice\runners\command_line_runner.py", line 12, in <module>
>   File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>   File "ice\runners\ice_engine.py", line 14, in <module>
>   File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>   File "ice\backups.py", line 10, in <module>
>   File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
>   File "ice\logs.py", line 66, in <module>
>   File "ice\logs.py", line 53, in create_logger
>   File "logging\handlers.py", line 117, in **init**
>   File "logging\handlers.py", line 64, in **init**
>   File "logging__init__.py", line 903, in **init**
>   File "logging__init__.py", line 926, in _open
> IOError: [Errno 2] No such file or directory: u'C:\Users\Chris\AppData\Local\Scott Rice\Ice\ice.log'

**Comment by tajnymag** [comment]
I have the same issue. As I have Python installed and available globally, I don't really think that absence of Python on your system is the main problem.

**Comment by Teutonic84** [comment]
I've found that you have to create the folder structure referenced on that last line above:

> IOError: [Errno 2] No such file or directory: u'C:\Users\Chris\AppData\Local\Scott Rice\Ice\ice.log'.

So just create the folder structure for "C:\Users\Chris\AppData\Local\Scott Rice\Ice". Then it should work. That's what fixed it for me. If anyone is using batch files with Ice, use the commands below to check to see if that folder is there and it not then create it before running Ice.

`
if not exist "%userprofile%\AppData\Local\Scott Rice\Ice" (mkdir "%userprofile%\AppData\Local\Scott Rice\Ice")
`

**Comment by imkrut** [comment]
@Teutonic84 Worked wonders, thanks for the help!
