### ISSUE TITLE
[TypeError:'NoneType' object is not iterable] when exec python -m ice

### ISSUE THREAD

**Issue by Marukesu** [scottrice/Ice#406]
when I run `python -m ice`  happens this error:

```
gustavo@IamSad:~/Downloads/Ice-master$ python -m ice.py
/usr/bin/python: No module named ice.py
gustavo@IamSad:~/Downloads/Ice-master$ sudo python -m ice.py
/usr/bin/python: No module named ice.py
gustavo@IamSad:~/Downloads/Ice-master$ sudo python -m ice
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice/decorators.py", line 10, in wrapped
    func(*args, **kwargs)
  File "ice/cli/runner.py", line 84, in run
    self.get_steam(app_settings.config),
  File "ice/tasks/engine.py", line 27, in __init__
    self.users = filter(is_user_context, steam_module.local_user_contexts(self.steam))
TypeError: 'NoneType' object is not iterable

Close the window, or hit enter to exit...
```

**Comment by balthazarbux** [comment]
Have you tried installing python-dev?

`sudo apt-get install python-dev`

**Comment by MrSadness** [comment]
worked, thanks

**Comment by mdhausman** [comment]
I'm having this same problem. I am using python-dev and followed the instructions.

``` console
maura@Mephistopheles:~/Software/Ice$ python --version
Python 2.7.12
maura@Mephistopheles:~/Software/Ice$ python -m ice
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice/decorators.py", line 10, in wrapped
    func(*args, **kwargs)
  File "ice/cli/runner.py", line 84, in run
    self.get_steam(app_settings.config),
  File "ice/tasks/engine.py", line 27, in __init__
    self.users = filter(is_user_context, steam_module.local_user_contexts(self.steam))
TypeError: 'NoneType' object is not iterable

Close the window, or hit enter to exit...

maura@Mephistopheles:~/Software/Ice$ 
```

**Comment by indivisible** [comment]
pysteam has a hardcoded path for linux that is sometimes incorrect. Try running `ln -s ~/.steam/steam ~/.local/share/Steam` in a terminal, it will probably fix it.

But this should really be fixed in the pysteam module.
