### ISSUE TITLE
Error: NoneType object has no attribute exe

### ISSUE THREAD

**Issue by Naetalis** [scottrice/Ice#449]
ICE was working fine in Steam with ZSNES for awhile. Today I tried adding Nestopia into the emulators & consoles text files and when running ICE it says it detects both ZSNES & Nestopia, but afterwards gives the above error in the subject line. Any idea what's going on?

**Comment by KcKuun** [comment]
I've gotten this same error starting about 2 days ago.  I was using  Retroarch for Nintendo 64 and was having a blast playing N64 games through Steam.  Then 2 days ago, I tried adding Dolphin for Wii games and was running into this error.  I got rid of Dolphin and re-installed all emulators and ice and fresh installed them and still got this error using the same settings I had before.  I am still able to play my old games I had added before, but I can't add new ones or consoles.  Checking the log shows the error as this: 

An Error has occurred:
'NoneType' object has no attribute 'exe'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 31, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 40, in __init__
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 52, in __is_managed_by_ice__
AttributeError: 'NoneType' object has no attribute 'exe'

**Comment by Naetalis** [comment]
Yep same, I can't add any new ROMs, but I still see my old ones.

**Comment by legendury** [comment]
I'm having the same issue. Same exact error as KcKuun

edit: I fixed this by deleting my shortcuts.vdf located in Steam\userdata\ (your account)\config and running Ice again.

**Comment by Naetalis** [comment]
This worked for me as well. Thanks!

**Comment by KcKuun** [comment]
Nice!  That worked for me too!  You are awesome!

**Comment by efinatto** [comment]
same here!

**Comment by Kenrohl** [comment]
Same error in the log, but delete this file dont change anything for me :'(

Any other idea ?

**Comment by uyuarasy** [comment]
+1, clean install, after the second scan I got the same error but the quick fix worked.

**Comment by Spiridios** [comment]
This issue is caused by Steam changing the file format. Pysteam (the library ICE uses to read/write the shortcuts file) doesn't understand how to parse the new format. There's a [bug](https://github.com/scottrice/pysteam/issues/12) logged against Pysteam about it. Blowing away the file allows ICE to write using the old format, and Steam will still happily read the old format. The only caveat is that if Steam writes to the file, it'll update the format and you'll be unable to use ICE again without blowing away the file.

**Comment by DocMAX** [comment]
waiting for a solution

**Comment by MarcelloLins** [comment]
For those that missed, @legendury  posted the solution. Deleting the file, while nor steam or are ice running solves the issue. Re-run ice again after deleting the file and the error should go away

**Comment by lachlankrautz** [comment]
If you want to get it going again try building from source with:
pysteam: https://github.com/scottrice/pysteam/pull/14
ice: https://github.com/scottrice/Ice/pull/456

**Comment by dijidiji** [comment]
I attempted to build lachlankrautz's commit into a binary and it seems to work (for me). First time doing this so my apologies if it doesn't work! It's also like twice the size of the official binaries, so I guess the method I used includes extra stuff or something.

One thing to note, I needed to remove %l from the commands in emulators.txt. Not sure if this is an error on my part or a consequence of the new shortcuts.vdf format.

Anyhow you're probably better off running it from source, but for those who can't this should work (I think).

[Ice.zip](https://github.com/scottrice/Ice/files/884095/Ice.zip)

**Comment by lachlankrautz** [comment]
Yeah so I changed the commands field to map to the launch options field in the steam shortcut so there is no longer a need for the exe "%i" in that field. 

This was because the shortcuts I made with params in the exe field didn't seem to work. I figured steam now wants exe in their "exe" field and params in their "launch options" field.

**Comment by genericusernam10** [comment]
For those thinking of trying the "delete shortcuts.vdf" workaround it will delete **all** shortcuts from your Steam library, and only those of your ROMs will be readded by ICE. Don't use this method if you have lots of shortcuts (any non-steam game/program) and make sure to backup the file even if you don't.

**Comment by UndarkAido** [comment]
When trying to build @lachlankrautz 's branch myself with pyinstaller, I get [<error.log gist>](https://gist.github.com/Aidoboy/09d56617a751b761d81bcf8fee674152) when I try to run it.

When I try to run @dijicaek 's executable, I get [<command line output gist>](https://gist.github.com/Aidoboy/34057e4d7198f1465f502b2d5b1cd695).

Does anyone know what's wrong?

**Comment by davasqueza** [comment]
I see that the problem comes when ICE try to read the shortcuts array generated by pysteam `shortcuts.get_shortcuts(user)` , the last position is of type "None" and this break all the process, a fast workarround is filtering the shortcuts array, like this:

backups.py - Line 66
```
shortcuts_list = shortcuts.get_shortcuts(user)
shortcuts.write_shortcuts(backup_path, [x for x in shortcuts_list if x is not None])
```

steam_shortcut_synchronizer.py - Line 76
```
current_shortcuts = shortcuts.get_shortcuts(user)
current_shortcuts = [x for x in current_shortcuts if x is not None]
```

I don't know if this is a bad solution but works for me

PD: sorry for my english

**Comment by Harribo19** [comment]
I downloaded ICE and got also this error.
Then I deleted the shortcut.vcf file.

After that there was no error.
But.. Steam did not show any shortcuts.
Have the latest version of Steam. 

So asking me, I think that ICE does not write the correct shortcut format any more. Steam changed the format (?) and ICE is not updated to this format.

Leaves me 1 question: how can I create a rom shortcut myself in steam? 

edit: got it:
RetroArch -L "C:\RetroArch\cores\(core).dll" (rom path)

**Comment by kwokhou** [comment]
Deleting `shortcut.vcf` actually delete all your existing steam shortcuts

**Comment by canichols2** [comment]
has there been any update on this? is there a way to fix it without blowing away all existing shortcuts?

**Comment by UndarkAido** [comment]
Nope, nothing. I would recommend Steam ROM Manager as an alternative.

**Comment by Teutonic84** [comment]
Is there someone who can recompile the ice.exe that dijicaek made above with the fixes that davasqueza found? I'd really appreciate it. I have it all working fine now except for having to delete shortcuts.vdf every time i want to import new ROMS.

**Comment by legendury** [comment]
Honestly just use Steam Room Manager. Works great and it's active

**Comment by Teutonic84** [comment]
I would use Steam Rom Manager if they added commandline support like ICE has, but they aren't going to be adding that anytime soon. I have ICE setup where i can just click on a link to a single batch file and it will auto-configure ICE, import the ROMS to steam and then open steam. i get that you can add everything from steam rom manager, but it's not as automated as i would like it to be.
