### ISSUE TITLE
ICE works on 1 account but not the other.

### ISSUE THREAD

**Issue by Nemesisthethird** [scottrice/Ice#483]
[09/17/17 21:05:16] 'NoneType' object has no attribute 'exe'
Traceback (most recent call last):
  File "<string>", line 45, in <module>
  File "<string>", line 31, in main
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 40, in __init__
  File "c:\Users\Scott.Scott-PC\Development\Projects\Ice\build\ice\out00-PYZ.pyz\ice.rom_manager", line 52, in __is_managed_by_ice__
AttributeError: 'NoneType' object has no attribute 'exe'
[09/17/17 21:05:16] ####################################

Latest issue.  Now its not due to the shortcut bug because I already deleted those both from my A and C steam files and inside of both accounts.  Currently my games transfer fine to 1 steam account but choose not to go to the other.

My config files and all are running correctly since they're just calling files, they're working and have nothing to do with the steam accounts directly. 

Not sure what's wrong.

**Comment by HEspoke** [comment]
SRM works with all user accounts by default. #473
