### ISSUE TITLE
Error - Can't find "Scott Ice\ice\ice.log"

### ISSUE THREAD

**Issue by groke76** [scottrice/Ice#490]
Does anybody have an idea what causes this error?

Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\command_line_runner.py", line 12, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\runners\ice_engine.py", line 14, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\backups.py", line 10, in <module>
  File "c:\program files (x86)\python27\lib\site-packages\PyInstaller-3.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "ice\logs.py", line 66, in <module>
  File "ice\logs.py", line 53, in create_logger
  File "logging\handlers.py", line 117, in __init__
  File "logging\handlers.py", line 64, in __init__
  File "logging\__init__.py", line 903, in __init__
  File "logging\__init__.py", line 926, in _open
IOError: [Errno 2] No such file or directory: u'C:\\Users\\kimme\\AppData\\Local\\Scott Rice\\Ice\\ice.log'

**Comment by stalonium** [comment]
Run the exe as Admin and in Windows 8 compatibility mode. If this doesn't help create the folder manually.

**Comment by tconroy** [comment]
In addition to above create the ROM folder manually and also the appData folder for the log file. Should work.

**Comment by ghost** [comment]
I'm also encountering this issue. Doing this for my Steam Link. I went ahead and created those folders and got past it, then it needed write access to my Steam/UserData/XXX fixed that. Now it needed backup location defined so fixed that, and now I'm to:
```
=========== Starting Ice ===========
Detected Emulator: RetroArch_SNES
Detected Console: Super Nintendo => RetroArch_SNES
=========== User: 10249471 ===========
[ERROR] An exception occurred while running Ice
Traceback (most recent call last):
  File "ice\decorators.py", line 9, in wrapped
  File "ice\runners\ice_engine.py", line 131, in run
  File "ice\runners\ice_engine.py", line 104, in create_backup
  File "ice\backups.py", line 67, in create_backup_of_shortcuts
  File "pysteam\shortcuts.py", line 30, in write_shortcuts
  File "pysteam\_shortcut_generator.py", line 20, in to_string
  File "pysteam\_shortcut_generator.py", line 29, in generate_array_string
  File "pysteam\_shortcut_generator.py", line 34, in generate_shortcut_string
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by Teutonic84** [comment]
What I did as a workaround to the 'NoneType' error, was delete my shortcuts.vdf file. Then put in the actual path to my steam userdata folder in ICE's "config.txt" file.  Ran ICE, it completed fine and worked after that. Sometimes it starts throwing that error again and I'll just delete the shortcuts.vdf file again.
