### ISSUE TITLE
cannot import name get_steam

### ISSUE THREAD

**Issue by bruno-f-cruz** [scottrice/Ice#491]
when running "python -m ice" after installation, i get:

Traceback (most recent call last):
  File "E:\SteamLibrary\emulator\Ice\ice\__main__.py", line 7, in <module>
    from cli import CommandLineRunner
  File "ice\cli\__init__.py", line 2, in <module>
    from runner import CommandLineRunner
  File "ice\cli\runner.py", line 10, in <module>
    from pysteam.steam import get_steam, Steam
ImportError: cannot import name get_steam

**Comment by spoink22** [comment]
I also have this issue... did you find a fix?

**Comment by a-chancey** [comment]
I'm SUPER late to the party, but I discovered the fix, for anyone else who stumbles upon this thread like I did:
If you manually installed the dependencies, the pysteam that PIP installs by default is not the correct pysteam version that is referenced by Ice. PIP only lists up to 0.1.3, which doesn't have the API calls that are in 1.0.0b2.

You'll want to run `pip uninstall pysteam`, then clone @scottrice's pysteam repository found [here.](https://github.com/scottrice/pysteam)

navigate to that directory, run 'python setup.py install', then hop back to the Ice directory, rebuild (re-run 'python setup.py install' in the Ice directory), and you should be good to go
