### ISSUE TITLE
UnicodeDecodeError: **

### ISSUE THREAD

**Issue by SpecklesShy** [scottrice/Ice#495]
2018-03-22 13:43:02,655 [DEBUG][steam_shortcut_synchronizer.py][sync_roms_for_user:98]: Saving shortcuts
2018-03-22 13:43:10,696 [ERROR][__init__.py][exception:1183]: An exception occurred while running Ice
Traceback (most recent call last):
  File "ice\decorators.py", line 9, in wrapped
  File "ice\runners\ice_engine.py", line 132, in run
  File "ice\steam_shortcut_synchronizer.py", line 99, in sync_roms_for_user
  File "pysteam\shortcuts.py", line 41, in set_shortcuts
  File "pysteam\shortcuts.py", line 30, in write_shortcuts
  File "pysteam\_shortcut_generator.py", line 20, in to_string
  File "pysteam\_shortcut_generator.py", line 29, in generate_array_string
  File "pysteam\_shortcut_generator.py", line 34, in generate_shortcut_string
  File "pysteam\_shortcut_generator.py", line 52, in generate_keyvalue_pair
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 4: ordinal not in range(128)

**Comment by SpecklesShy** [comment]
This is a bit beyond what I can interpret.

**Comment by bmarwell** [comment]
I'll have a guess.

One of your titles contains non-ASCII chars, but the author didn't use UTF-8 everywhere accidentally. That's one of python's disadvantages, imho. It's always a hazzle to get encoding and decoding right.

**Comment by SpecklesShy** [comment]
Thanks for your input. I'll go through my ROMs and see if I can correct that. To anyone else who's better at interpreting this than myself or @bmhm please let me know.
