### ISSUE TITLE
Error: Traceback...

### ISSUE THREAD

**Issue by SpecklesShy** [scottrice/Ice#496]
2018-04-02 14:11:46,765 [ERROR][__init__.py][exception:1183]: An exception occurred while running Ice
Traceback (most recent call last):
  File "ice\decorators.py", line 9, in wrapped
  File "ice\runners\ice_engine.py", line 131, in run
  File "ice\runners\ice_engine.py", line 104, in create_backup
  File "ice\backups.py", line 67, in create_backup_of_shortcuts
  File "pysteam\shortcuts.py", line 30, in write_shortcuts
  File "pysteam\_shortcut_generator.py", line 20, in to_string
  File "pysteam\_shortcut_generator.py", line 29, in generate_array_string
  File "pysteam\_shortcut_generator.py", line 34, in generate_shortcut_string
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ghost** [comment]
Ever get past this?

**Comment by SpecklesShy** [comment]
I haven't.

**Comment by Teutonic84** [comment]
I'm having the same exact issue. Anyone know a workaround? If I delete my shortcuts.vdf file ICE completes fine the first run after that. But then after opening steam and then trying to run ICE again it throws those errors.

UPDATE: I found a workaround, though it might not be for everyone. I deleted the shortcuts.vdf file, then put the path to the steam userdata folder in config.txt, ran ICE and now it seems to be working fine. I'll post here again if it stops working.

**Comment by UNiXMIT** [comment]
Same issue here and the proposed workaround doesn't fix it for me. Has anyone looked into this issue? Thanks

**Comment by Teutonic84** [comment]
There is a fix of sorts, but it requires you to edit some source files and rebuild from source. I was going to look into compiling an EXE with the fixes, but I have been way too busy lately to look into it. So if you're interested here's the fix: https://github.com/scottrice/Ice/pull/456 (it requires you to update pysteam which is an external library that ICE uses) and editing "backups.py" and "steam_shortcut_synchronizer.py" from here: https://github.com/scottrice/Ice/pull/499/files

If someone is able to get all these fixes implemented and compiled to a single EXE, this would be awesome. Then ICE would be back on top for importing ROMS to steam for me at least. :)

**Comment by UNiXMIT** [comment]
Great thanks I'll try it.

**Comment by bmarwell** [comment]
If this isn't fixed, there is always the possibility to fork it and develop it as a community project if the license will allow it.

**Comment by Teutonic84** [comment]
Does anyone have instructions on how to properly build Ice from source? I downloaded the latest Ice source files, and latest pysteam source files. Installed them into my python 2.7 framework on my windows 10 PC, but when i tried to build the source files into an EXE with pyinstaller, it wasn't working. pyinstaller finished without errors and i had an EXE, but when i tried to run it, i got an error. it's like it didn't import everything into the EXE.

**Comment by ssolidus** [comment]
@Teutonic84 I'm willing to help you with this. Could we discuss?

I noticed your "SteamConsole" repository. Is this related?

**Comment by Teutonic84** [comment]
Sorry for the late reply @ssolidus Yes this is related to my SteamConsole repository. I'd love to have some help with this. Currently I have to delete the steam shortcuts.vdf file everytime i have my script import ROMs to steam. Not ideal.

**Comment by vvvvkennyvvvv** [comment]
TAKE ME OFF THIS FUCKING LIST GOD DAMMIT ITS BEEN 4 YEARS

**Comment by ssolidus** [comment]
@vvvvkennyvvvv There's a button on the top right to turn off notifications, lol

**Comment by vvvvkennyvvvv** [comment]
I FUCKING CANT BECAUSE I MADE THIS DUMB ASS ACCOUNT 4 YEARS AGO AND CANT
GET INTO I CAN ONLY REPLY VIA EMAIL AND NO MATTER HOW MANY FUCKING TIMES I
MUTE OR REPORT IT AS SPAM IT KEEPS COMING UP

**Comment by bmarwell** [comment]
@vvvvkennyvvvv Screaming does not help. Look in your inbox such exact mail address you're receiving mails. Then click forgot password, then log in, then unsubscribe.

If that does not help, contact GitHub support. But PLEASE stop posting here.

Meanwhile, why not just set up a mail filter?

That's faster than posting here or reading all of this.

**Comment by ssolidus** [comment]
@bmhm I think he's just an idiot.

@Teutonic84 if you want to post your Steam or email, I'd like to help you out

**Comment by Teutonic84** [comment]
@ssolidus here's my email: crazyotaku61@gmail.com  thanks!
